name: build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check
      run: /usr/bin/dotnet --version

    - name: Clean Pack
      run: ./build.sh clean pack
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./artifacts/*
